Added simple logging
Project-Summer-AI-Lab-Glider/nurse-scheduling-problem-solver pull request #31
Opened 2021-02-17 12:55 UTC by Thematiq

Teraz wszystkie informacje przekazywane do logging (_@info, @error_) oraz harmonogramy otrzymywane powinny być zapisywane do plików według _logConstants.jl_. Jak uda mi się odpalić frontend, żeby sprawdzić czy działa wszystko to zmienię z drafta.

2021-02-20 09:47 UTC, prenc requested changes
Małe zmiany i doprezycownia, dobra robota!

2021-02-20 09:47 UTC, prenc commented on src/logger.jl
> +        )))) + 1
Nie wiadomo co tutaj się dzieje, zapisz do zmiennych poszczególne części.

2021-02-20 09:47 UTC, prenc commented on src/logConstants.jl
> +STD_LOG = "./logs/std.txt"
Może tę nazwę zmień lekko, STD_LOG.

2021-02-20 09:47 UTC, prenc commented on src/logConstants.jl
> +SAVE_STD = true
Czy jak jest na false, to logi są przekazywane na stdout?

2021-02-22 20:01 UTC, Thematiq commented
Ogarnięte do końca, przetestowane z aplikacją. Schedule logują się do _logs/requests/_ z kolejnymi ID, gdzie przy każdym zapisie jest ono logowane do głównego loggera. Okazało się, że standardowe loggery nie starczają do jednoczesnego zapisu w dwa miejsca, więc dodałem libkę.

2021-02-23 01:09 UTC, prenc approved these changes
Wszystko wygląda dobrze, merguje

2021-02-23 01:10 UTC, merged